<?php

return [
    'books' => [
        [
            "id" => 1,
            "is_reading" => false,
            "progress" => 0,
            "title" => "C",
            "genre" => "Classic",
            "description" => "A story about the American dream and societal excess.",
            "rating" => 4.7,
            "author" => "F. Scott Fitzgerald",
            "synopsis" => "Nick Carraway, a young man from Minnesota, moves to New York in the summer of 1922. He rents a house in West Egg, a wealthy but unfashionable area populated by the new rich...",
            "cover_url" => "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.eTO09xqdGYiKU913AIb0vQHaJt%26pid%3DApi&f=1&ipt=8b2cd3cbe620af9e1eabee3afd92b884502d9bf18dc9cca36e7ca14281b09239&ipo=images",
            "tags" => "Trending",
            "publication_date" => "1925/10/01",
            "number_of_pages" => 180,
            "publisher" => "Scribner",
            "language" => "English",
            "characters" => ["Jay Gatsby", "Nick Carraway", "Daisy Buchanan"]
        ],
        [
            "id" => 2,
            "is_reading" => false,
            "progress" => 0,
            "title" => "To Kill a Mockingbird",
            "genre" => "Historical Fiction",
            "description" => "A powerful tale of racial injustice in the Deep South.",
            "rating" => 4.9,
            "author" => "Harper Lee",
            "synopsis" => "The story takes place in the fictional town of Maycomb, Alabama, during the 1930s. Scout Finch recounts her childhood and the events surrounding her father, Atticus Finch...",
            "cover_url" => "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.W1ngiF2AkQaO78CY9yC1HQHaLd%26pid%3DApi&f=1&ipt=ff7748ba7d4d167c48ac057b0ddfd02601983594a316f4ac5d03fb58053ad3e6&ipo=images",
            "tags" => "Trending",
            "publication_date" => "1960/10/01",
            "number_of_pages" => 281,
            "publisher" => "J.B. Lippincott & Co.",
            "language" => "English",
            "characters" => ["Scout Finch", "Atticus Finch", "Tom Robinson"]
        ],
        [
            "id" => 3,
            "is_reading" => false,
            "progress" => 0,
            "title" => "1984",
            "genre" => "Dystopian",
            "description" => "A chilling depiction of a totalitarian regime and extreme surveillance.",
            "rating" => 4.8,
            "author" => "George Orwell",
            "synopsis" => "The novel is set in Airstrip One, formerly Great Britain, a province of the superstate Oceania. The world is perpetually at war, and the government, known as the Party...",
            "cover_url" => "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.explicit.bing.net%2Fth%3Fid%3DOIP.5fghEVBNKHeSYr8tyg-tVgHaLW%26pid%3DApi&f=1&ipt=ae56c81a3f2a5e1b1222b74e4ffd195cd718155479b18f2f2e8aa32b1e2554f1&ipo=images",
            "tags" => "Trending",
            "publication_date" => "1949/10/01",
            "number_of_pages" => 328,
            "publisher" => "Secker & Warburg",
            "language" => "English",
            "characters" => ["Winston Smith", "Julia", "O'Brien"]
        ],
        [
            "id" => 4,
            "is_reading" => false,
            "progress" => 0,
            "title" => "Pride and Prejudice",
            "genre" => "Romance",
            "description" => "A classic love story set in Regency England.",
            "rating" => 4.6,
            "author" => "Jane Austen",
            "synopsis" => "Elizabeth Bennet, the intelligent and spirited second daughter of five, navigates societal expectations and her own feelings for Mr. Darcy...",
            "cover_url" => "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.mhFI3Nd75_9KE06fiw-XGAHaKN%26pid%3DApi&f=1&ipt=c673bd6051d05204a744b5776e10a7a564488a006fc1599379571f86f5c53be9&ipo=images",
            "tags" => "Trending",
            "publication_date" => "1813/10/01",
            "number_of_pages" => 279,
            "publisher" => "T. Egerton",
            "language" => "English",
            "characters" => ["Elizabeth Bennet", "Mr. Darcy", "Jane Bennet"]
        ],
        [
            "id" => 5,
            "is_reading" => false,
            "progress" => 0,
            "title" => "The Catcher in the Rye",
            "genre" => "Fiction",
            "description" => "A story about teenage rebellion and self-discovery.",
            "rating" => 4.5,
            "author" => "J.D. Salinger",
            "synopsis" => "Holden Caulfield, a teenager in New York City, recounts his experiences after being expelled from a prestigious boarding school. Struggling with alienation, he searches for meaning in a world he finds hypocritical.",
            "cover_url" => "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.WIlTXUUOYa6nqscRw9Gx6AHaKn%26pid%3DApi&f=1&ipt=d3223311801a3a8a20393372f42db528632b4d638e33c318cb34d033bc40a930&ipo=images",
            "tags" => "Favorite",
            "publication_date" => "1951/10/01",
            "number_of_pages" => 214,
            "publisher" => "Little, Brown and Company",
            "language" => "English",
            "characters" => ["Holden Caulfield", "Phoebe Caulfield", "Mr. Antolini"]
        ],
        [
            "id" => 6,
            "is_reading" => true,
            "progress" => 72,
            "title" => "Brave New World",
            "genre" => "Dystopian",
            "description" => "A vision of a technologically advanced but controlled society.",
            "rating" => 4.7,
            "author" => "Aldous Huxley",
            "synopsis" => "Set in a futuristic World State, where society is highly regulated, individuals are conditioned to conform, and emotions are suppressed. Bernard Marx and John the Savage explore the cost of utopia.",
            "cover_url" => "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.n0tZZdC8maTk4BMLcTKFoAHaLY%26pid%3DApi&f=1&ipt=5f3ccdf4cb59cc54d6a8f94fb9a67b4a638456421b4cccde2dc922f88fecba9b&ipo=images",
            "tags" => "Favorite",
            "publication_date" => "1932/10/01",
            "number_of_pages" => 311,
            "publisher" => "Chatto & Windus",
            "language" => "English",
            "characters" => ["Bernard Marx", "John the Savage", "Lenina Crowne"]
        ],
        [
            "id" => 7,
            "is_reading" => false,
            "progress" => 0,
            "title" => "Moby Dick",
            "genre" => "Adventure",
            "description" => "A tale of obsession and revenge on the high seas.",
            "rating" => 4.4,
            "author" => "Herman Melville",
            "synopsis" => "Captain Ahab, driven by vengeance, embarks on a perilous journey to hunt the elusive white whale, Moby Dick, while exploring themes of fate, nature, and humanity.",
            "cover_url" => "https://m.media-amazon.com/images/I/71d5wo+-MuL.jpg",
            "tags" => "Classic",
            "publication_date" => "1851/10/01",
            "number_of_pages" => 635,
            "publisher" => "Harper & Brothers",
            "language" => "English",
            "characters" => ["Captain Ahab", "Ishmael", "Queequeg"]
        ],
        [
            "id" => 8,
            "is_reading" => true,
            "progress" => 12,
            "title" => "War and Peace",
            "genre" => "Historical Fiction",
            "description" => "An epic novel of Russian society during the Napoleonic Wars.",
            "rating" => 4.6,
            "author" => "Leo Tolstoy",
            "synopsis" => "Through the lives of Pierre, Natasha, and Andrei, Tolstoy examines the impact of war on society, personal struggles, and the human condition.",
            "cover_url" => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2e3wdnr5E28WIddaoAjaeI3LVPKzXfMFdKA&s",
            "tags" => "Classic",
            "publication_date" => "1869/10/01",
            "number_of_pages" => 1225,
            "publisher" => "The Russian Messenger",
            "language" => "Russian",
            "characters" => ["Pierre Bezukhov", "Natasha Rostova", "Andrei Bolkonsky"]
        ],
        [
            "id" => 9,
            "is_reading" => false,
            "progress" => 0,
            "title" => "The Hobbit",
            "genre" => "Fantasy",
            "description" => "A prelude to the epic Lord of the Rings saga.",
            "rating" => 4.8,
            "author" => "J.R.R. Tolkien",
            "synopsis" => "Bilbo Baggins, a reluctant hobbit, embarks on a daring adventure to help a group of dwarves reclaim their homeland from the dragon Smaug.",
            "cover_url" => "https://m.media-amazon.com/images/I/712cDO7d73L.jpg",
            "tags" => "Favorite",
            "publication_date" => "1937/10/01",
            "number_of_pages" => 310,
            "publisher" => "George Allen & Unwin",
            "language" => "English",
            "characters" => ["Bilbo Baggins", "Gandalf", "Thorin Oakenshield"]
        ]
    ]
];
