<?php

return [
    'books' => [
        [
            "id" => 1,
            "on_read" => false,
            "read_percentage" => 0,
            "title" => "The Great Gatsby",
            "genre" => "Classic",
            "description" => "A story about the American dream and societal excess.",
            "rating" => 4.7,
            "author" => "F. Scott Fitzgerald",
            "synopsis" => "Nick Carraway, a young man from Minnesota, moves to New York in the summer of 1922. He rents a house in West Egg, a wealthy but unfashionable area populated by the new rich...",
            "cover_url" => "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.eTO09xqdGYiKU913AIb0vQHaJt%26pid%3DApi&f=1&ipt=8b2cd3cbe620af9e1eabee3afd92b884502d9bf18dc9cca36e7ca14281b09239&ipo=images",
            "tags" => "Trending"
        ],
        [
            "id" => 2,
            "on_read" => false,
            "read_percentage" => 0,
            "title" => "To Kill a Mockingbird",
            "genre" => "Historical Fiction",
            "description" => "A powerful tale of racial injustice in the Deep South.",
            "rating" => 4.9,
            "author" => "Harper Lee",
            "synopsis" => "The story takes place in the fictional town of Maycomb, Alabama, during the 1930s. Scout Finch recounts her childhood and the events surrounding her father, Atticus Finch...",
            "cover_url" => "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.W1ngiF2AkQaO78CY9yC1HQHaLd%26pid%3DApi&f=1&ipt=ff7748ba7d4d167c48ac057b0ddfd02601983594a316f4ac5d03fb58053ad3e6&ipo=images",
            "tags" => "Trending"
        ],
        [
            "id" => 3,
            "on_read" => false,
            "read_percentage" => 0,
            "title" => "1984",
            "genre" => "Dystopian",
            "description" => "A chilling depiction of a totalitarian regime and extreme surveillance.",
            "rating" => 4.8,
            "author" => "George Orwell",
            "synopsis" => "The novel is set in Airstrip One, formerly Great Britain, a province of the superstate Oceania. The world is perpetually at war, and the government, known as the Party...",
            "cover_url" => "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.explicit.bing.net%2Fth%3Fid%3DOIP.5fghEVBNKHeSYr8tyg-tVgHaLW%26pid%3DApi&f=1&ipt=ae56c81a3f2a5e1b1222b74e4ffd195cd718155479b18f2f2e8aa32b1e2554f1&ipo=images",
            "tags" => "Trending"
        ],
        [
            "id" => 4,
            "on_read" => false,
            "read_percentage" => 0,
            "title" => "Pride and Prejudice",
            "genre" => "Romance",
            "description" => "A classic love story set in Regency England.",
            "rating" => 4.6,
            "author" => "Jane Austen",
            "synopsis" => "Elizabeth Bennet, the intelligent and spirited second daughter of five, navigates societal expectations and her own feelings for Mr. Darcy...",
            "cover_url" => "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.mhFI3Nd75_9KE06fiw-XGAHaKN%26pid%3DApi&f=1&ipt=c673bd6051d05204a744b5776e10a7a564488a006fc1599379571f86f5c53be9&ipo=images",
            "tags" => "Trending",
        ],
        [
            "id" => 5,
            "on_read" => false,
            "read_percentage" => 0,
            "title" => "The Catcher in the Rye",
            "genre" => "Fiction",
            "description" => "A story about teenage rebellion and self-discovery.",
            "rating" => 4.5,
            "author" => "J.D. Salinger",
            "synopsis" => "Holden Caulfield, a teenager in New York City, recounts his experiences after being expelled from a prestigious boarding school. Struggling with alienation, he searches for meaning in a world he finds hypocritical.",
            "cover_url" => "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.WIlTXUUOYa6nqscRw9Gx6AHaKn%26pid%3DApi&f=1&ipt=d3223311801a3a8a20393372f42db528632b4d638e33c318cb34d033bc40a930&ipo=images",
            "tags" => "Favorite",
        ],
        [
            "id" => 6,
            "on_read" => true,
            "read_percentage" => 72,
            "title" => "Brave New World",
            "genre" => "Dystopian",
            "description" => "A vision of a technologically advanced but controlled society.",
            "rating" => 4.7,
            "author" => "Aldous Huxley",
            "synopsis" => "Set in a futuristic World State, where society is highly regulated, individuals are conditioned to conform, and emotions are suppressed. Bernard Marx and John the Savage explore the cost of utopia.",
            "cover_url" => "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.n0tZZdC8maTk4BMLcTKFoAHaLY%26pid%3DApi&f=1&ipt=5f3ccdf4cb59cc54d6a8f94fb9a67b4a638456421b4cccde2dc922f88fecba9b&ipo=images",
            "tags" => "Favorite",
        ],
        [
            "id" => 7,
            "on_read" => false,
            "read_percentage" => 0,
            "title" => "The Hobbit",
            "genre" => "Fantasy",
            "description" => "A tale of adventure, friendship, and courage.",
            "rating" => 4.8,
            "author" => "J.R.R. Tolkien",
            "synopsis" => "Bilbo Baggins, a hobbit, is thrust into an epic quest to help a group of dwarves reclaim their homeland from the dragon Smaug. Along the way, he discovers courage and resourcefulness he never knew he had.",
            "cover_url" => "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.iUd0FIdWSJHPGMizJ1LCvwHaLX%26pid%3DApi&f=1&ipt=9c953b66bdb28e2be14f19c8dcf3ffbac6fc7c3e5247924bf5aa4e6513ead236&ipo=images",
            "tags" => "Favorite",

        ],
        [
            "id" => 8,
            "on_read" => true,
            "read_percentage" => 12,
            "title" => "The Alchemist",
            "genre" => "Adventure",
            "description" => "An inspiring journey of self-discovery.",
            "rating" => 4.6,
            "author" => "Paulo Coelho",
            "synopsis" => "Santiago, a shepherd boy, travels from Spain to the Egyptian desert in search of a treasure. Along the way, he learns valuable lessons about life, love, and following one's dreams.",
            "cover_url" => "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.9-v0mfum2BK2IFqSLAXf3gHaL7%26pid%3DApi&f=1&ipt=c684e2ff506935ec34b4b61ab3708cfb11b41bbab0015aa27c41d984c81f3c82&ipo=images",
            "tags" => "Favorite",
        ],
        [
            "id" => 9,
            "on_read" => false,
            "read_percentage" => 0,
            "title" => "Harry Potter and the Sorcerer's Stone",
            "genre" => "Fantasy",
            "description" => "The beginning of a magical adventure.",
            "rating" => 4.9,
            "author" => "J.K. Rowling",
            "synopsis" => "Harry Potter discovers he is a wizard on his 11th birthday. He attends Hogwarts School of Witchcraft and Wizardry, where he makes friends, learns magic, and uncovers secrets about his past.",
            "cover_url" => "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.oXoJVYS11aDoXbnm4I2alwHaLH%26pid%3DApi&f=1&ipt=c29357e69db19ac208d3888ee044b2593b50315f41762598403d6263b6549e5b&ipo=images",
            "tags" => "Favorite",
        ]
    ]
];
